GPU_ID=$1
jac-crun ${GPU_ID} scripts/trainval_tube_v2.py --desc clevrer/desc_nscl_derender_clevrer_v2.py\
    --batch-size 1 --epoch 30 \
    --validation-interval 5 \
    --save-interval 5 \
    --normalized_boxes 1 \
    --rel_box_flag 0 --acc-grad 1 --dynamic_ftr_flag  1 \
    --box_iou_for_collision_flag 1 \
    --diff_for_moving_stationary_flag 1 \
    --new_mask_out_value_flag 1 \
    --apply_gaussian_smooth_flag 1 \
    --colli_ftr_type 1 \
    --frm_img_num 31 --even_smp_flag 1 \
    --lr 0.0001 \
    --tube_mode 1 \
    --version v2 \
    --prefix billiards_sup \
    --dataset billiards --data-dir ../clevrer/billiards \
    --question_path ../question_billiards/dump/questions \
    --tube_prp_path ../clevrer/tubeProposalsAttrMatchNoIoUThre/1.0_1.0_0.6_0.7 \
    --frm_img_path ../clevrer/billiards/realb_public \
    --data-workers 2 \
    --scene_gt_path ../clevrer/billiards/video_annotations \
    --scene_supervision_flag 1 \
    --scene_supervision_weight 0.5 \
    --scene_add_supervision 0 \
