python scripts/script_gen_tube_proposals.py \
    --start_index 10000 \
    --end_index 15000 \
    --attr_w 0.6 \
    --match_thre 0.7 \
    --version 2 \
    --visualize_flag 0 \
    --tube_folder_path ../clevrer/tubeProposalsRelease \
    --use_attr_flag 0 \
